version: 2
jobs:
  build:
    macos:
      xcode: '10.1.0'
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            brew install swiftlint
            brew install carthage
      - run:
          name: Fetch dependencies
          command: |
            carthage update --platform macos
      - run:
          name: Generate Xcode project
          command: |
            swift package generate-xcodeproj
      - run:
          name: Build
          command: |
            swift build
      - run:
          name: Run tests
          command: xcodebuild test -scheme Simulator-Package -project Simulator.xcodeproj -enableCodeCoverage YES

      - run:
          name: Build Carthage project
          command: |
            xcodebuild build -scheme Simulator -project Simulator-Carthage.xcodeproj
      - run:
          name: Send test coverage report
          command: bash <(curl -s https://codecov.io/bash)
